apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.app.name }}"
spec:
  type: ClusterIP 
  ports:
  - name: http
    port: 8080
    protocol: TCP
  selector:
    app: "{{ .Values.app.name }}"
